### ISSUE TITLE
OSError: Unknown template 'isyntax2raw.resources.ome_template'

### ISSUE THREAD

**Issue by Yadav420dilip** [glencoesoftware/isyntax2raw#12]
After executing the command  for convetring isyntax format  image into tile

**isyntax2raw write_tiles /home/dilip/pathology/isyntax/abcd.isyntax /home/dilip/pathology/tile_image**
It throw the error

**Traceback (most recent call last):**
  File "/usr/local/bin/isyntax2raw", line 11, in <module>
    load_entry_point('isyntax2raw==0.0.0', 'console_scripts', 'isyntax2raw')()
  File "/usr/local/lib/python3.6/dist-packages/isyntax2raw-0.0.0-py3.6.egg/isyntax2raw/cli/isyntax2raw.py", line 63, in main
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/isyntax2raw-0.0.0-py3.6.egg/isyntax2raw/cli/isyntax2raw.py", line 53, in write_tiles
  File "/usr/local/lib/python3.6/dist-packages/isyntax2raw-0.0.0-py3.6.egg/isyntax2raw/__init__.py", line 240, in write_metadata
  File "/usr/local/lib/python3.6/dist-packages/Kajiki-0.8.2-py3.6.egg/kajiki/loader.py", line 73, in import_
    filename = self._filename(name)
  File "/usr/local/lib/python3.6/dist-packages/Kajiki-0.8.2-py3.6.egg/kajiki/loader.py", line 124, in _filename
    raise IOError('Unknown template %r' % name)
OSError: Unknown template 'isyntax2raw.resources.ome_template'

The above command sometime work or sometime not work.
When it not work that time it  only create the METADATA.json file.

**When it successfully convert the image into tile then i apply the following command to convert tiles into OME-TIFF format**

 **bin/raw2ometiff-master /home/dilip/pathology/tile_image /home/dilip/pyramid.ome.tiff**

then it again throw the error

2020-04-01 20:21:27,944 [main] INFO  org.perf4j.TimingLogger - start[1585752687893] time[49] tag[initialize]
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.pyramid.PyramidFromDirectoryWriter@46238e3f): java.lang.RuntimeException: loci.formats.FormatException: Could not create an N5 reader
	at picocli.CommandLine.execute(CommandLine.java:1180)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at picocli.CommandLine.call(CommandLine.java:1786)
	at picocli.CommandLine.call(CommandLine.java:1710)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.main(PyramidFromDirectoryWriter.java:260)
Caused by: java.lang.RuntimeException: loci.formats.FormatException: Could not create an N5 reader
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:291)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:97)
	at picocli.CommandLine.execute(CommandLine.java:1173)
	... 8 more
Caused by: loci.formats.FormatException: Could not create an N5 reader
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.initialize(PyramidFromDirectoryWriter.java:501)
	at com.glencoesoftware.pyramid.PyramidFromDirectoryWriter.call(PyramidFromDirectoryWriter.java:277)

**Comment by melissalinkert** [comment]
```
isyntax2raw write_tiles /home/dilip/pathology/isyntax/abcd.isyntax /home/dilip/pathology/tile_image
It throw the error
...
raise IOError('Unknown template %r' % name)
OSError: Unknown template 'isyntax2raw.resources.ome_template'
```

We have seen this before with isyntax2raw installations from an egg, but it should have been fixed with https://github.com/glencoesoftware/isyntax2raw/pull/9.  Can you provide the exact steps (including specific commands) that you used to download and install isyntax2raw?

```
When it successfully convert the image into tile then i apply the following command to convert tiles into OME-TIFF format

bin/raw2ometiff-master /home/dilip/pathology/tile_image /home/dilip/pyramid.ome.tiff

then it again throw the error

2020-04-01 20:21:27,944 [main] INFO org.perf4j.TimingLogger - start[1585752687893] time[49] tag[initialize]
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.pyramid.PyramidFromDirectoryWriter@46238e3f): java.lang.RuntimeException: loci.formats.FormatException: Could not create an N5 reader
```

This usually means that the tiles were not written.  Does the output of the ```ls -hl /home/dilip/pathology/tile_image/``` command show that there is a ```pyramid.n5``` directory?  If not, the tiles were not written and ```raw2ometiff``` should not be run.

**Comment by Yadav420dilip** [comment]
**Can you provide the exact steps (including specific commands) that you used to download and install isyntax2raw?**

First I download the [isyntax2raw](https://github.com/glencoesoftware/isyntax2raw).
After that unzip the zip file then i apply following command to install isyntax2raw

$ cd isyntax2raw-master
$ python3 setup.py build
$ python3 setup.py install

**Comment by chris-allan** [comment]
If you are having problems building from source, in particular with the XML templates, please install the prebuilt wheels from the releases:

 * https://github.com/glencoesoftware/isyntax2raw/releases
