### ISSUE TITLE
Issues in installation of pathology sdk with anaconda

### ISSUE THREAD

**Issue by maths-qureshi** [glencoesoftware/isyntax2raw#19]
Hi,

I have installed the Pathology SDK and the relevant egg files can be found in the site-packages directory. But the system is unable to load the relevant dlls. I have added the directory containing the dll in the path and also manually copied the relevant directories in to site packages. But it does not help. I am using the latest Anaconda. Here is the error log:
 Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\isyntax2raw-script.py", line 33, in <module>
    sys.exit(load_entry_point('isyntax2raw==0.0.0', 'console_scripts', 'isyntax2raw')())
  File "C:\Anaconda3\Scripts\isyntax2raw-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Anaconda3\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Anaconda3\lib\site-packages\isyntax2raw-0.0.0-py3.8.egg\isyntax2raw\__init__.py", line 17, in <module>
ImportError: DLL load failed while importing pixelengine: The specified module could not be found.

**Comment by chris-allan** [comment]
Before going any further with `isyntax2raw` I would first make sure that the `pixelengine` module from the Pathology SDK is usable from your Anaconda runtime. The Pathology SDK is also distributed in binary form so the major Python version (3.7) is likely to need to match exactly.
