### ISSUE TITLE
i am facing issue module not found

### ISSUE THREAD

**Issue by krushnavadan** [glencoesoftware/isyntax2raw#23]
syntax E:\Solution\imps\testdata\test
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\isyntax2raw-script.py", line 33, in <module>
    sys.exit(load_entry_point('isyntax2raw==0.0.0', 'console_scripts', 'isyntax2raw')())
  File "C:\Program Files\Python39\Scripts\isyntax2raw-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Program Files\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Program Files\Python39\lib\site-packages\isyntax2raw-0.0.0-py3.9.egg\isyntax2raw\__init__.py", line 17, in <module>

**Comment by melissalinkert** [comment]
@krushnavadan : it looks like part of the error message is missing.  Could you please:

- paste the entire error message
- tell us which version of ```isyntax2raw``` you have installed
- tell us which version of Philips' SDK you have installed

**Comment by krushnavadan** [comment]
raceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\isyntax2raw-script.py", line 33, in <module>
    sys.exit(load_entry_point('isyntax2raw==0.0.0', 'console_scripts', 'isyntax2raw')())
  File "C:\Program Files\Python39\Scripts\isyntax2raw-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Program Files\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Program Files\Python39\lib\site-packages\isyntax2raw-0.0.0-py3.9.egg\isyntax2raw\__init__.py", line 17, in <module>
ImportError: DLL load failed while importing pixelengine: The specified module could not be found.

**Comment by krushnavadan** [comment]
philips-pathologysdk-2.0-windows10-py37-research

**Comment by chris-allan** [comment]
The Philips Pathology SDK specifically requires the same Python version (3.7) be used in order to function correctly. You are using Python 3.9.

**Comment by idc9** [comment]
@chris-allan Do you have any suggestions for installing the SDK? Specifically how to handle the python version issue? My system python is 3.9 and the SDK package I have is for 3.8. I tried creating a conda environment and installing, but the SDK still doesn't show up in python...
